### ISSUE TITLE
Motivación y ejemplos del curso (pandas)

### ISSUE THREAD

**Issue by franktoffel** [CAChemE/python-analisis-modelado-datos#1]
El ejemplo con los datos de Alicante está genial. 

Durante la instalación de Anaconda, podríais contarle vuestras anécdotas de por qué necesitan "complicarse la vida" con pandas y/o scikit learn.

Digo esto porque, con pandas, acabáis con los gráficos después de pelearos con carga, parseo de fechas, etc. Hay un riesgo de perder a parte de los alumnos, ya que Excel también podría importar estos datos y no tienen que aprender algo nuevo. 

¿Cúando falla Excel? ¿qué empresas usan pandas?

- Muchos archivos de tamaño pesado
- VBA es sólo dentro de Microsoft
- Control de cambios en la hoja
- etc

Aquí pongo dos ejemplos de datos con papers (seguir links al final) donde se ven los gráficos y se puede entender (antes de empezar) que para monitorización y predicción es mejor automatizar el análisis de datos.

https://archive.ics.uci.edu/ml/datasets/Air+Quality
https://archive.ics.uci.edu/ml/datasets/SML2010

**Comment by AlexS12** [comment]
Nos parece una buena idea! tienen que quedar claras las ventajas =)
